apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  namespace: production
  labels:
    app: hello-world
    env: production
    ver: v1
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  minReadySeconds: 10
  selector:
    matchLabels:
      app: hello-world
      env: production
      ver: v1
  template:
    metadata:
      labels:
        app: hello-world
        env: production
        ver: v1
    spec:
      containers:
      - name: hello-world
        image: kubejack/helloworld-production:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
           httpGet:
             # Path to probe; should be cheap, but representative of typical behavior
             path: /
             port: 3000
           initialDelaySeconds: 30
           timeoutSeconds: 1
        resources:
           limits:
             cpu: 300m
             memory: 50Mi
           requests:
             cpu: 300m
             memory: 50Mi
