apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  labels:
    name: hello-world-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP 
  selector:
    app: hello-world
    env: production
    ver: v1
